source("tasks/config.R")
source("tasks/api-wahlrechtde-umfragen.R")
source("tasks/calculations.R")
source("tasks/chart-longterm-polls.R")
source("tasks/chart-sunday-polls.R")
system("node tasks/buildReadme")
