source("tasks/config.R")
# source("tasks/api-wahlrechtde-umfragen.R")
source("tasks/scrape-wahlrechtde-umfragen.R")
#source("tasks/calculations.R")
source("tasks/calculations_gauss.R")
source("tasks/chart-longterm-polls.R")
#source("tasks/chart-sunday-polls.R")
source("tasks/chart-sunday-polls-gauss.R")
system("node tasks/buildReadme")

